name: Swift

on:
  push:
    branches:
      - main 
      - develop
      - feature/*
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
  
  # Initialize Build Environment
    name: Initialize
    env: 
      DEVICE: "iPhone 12"
      DERIVED_DATA_PATH: "DerivedData"
  
    runs-on: macos-latest

    steps:
    
    # Checkout build branch
    - name: Checkout
      uses: actions/checkout@v2
    
    # Run bundler
    - name: Run Bundler
      run: |
       bundle update
       
    # Execute Builds 
    - name: Build 
      run: bundle exec fastlane ios test
    
    # Run tests
