name: Swift

on:
  push:
    branches:
      - main 
      - develop
      - feature/*
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
  
  # Initialize Build Environment
    name: Initialize
    env: 
      DEVICE: "iPhone 12"
      DERIVED_DATA_PATH: "DerivedData"
  
    runs-on: macos-latest

    steps:
    
    # Checkout build branch
    - name: Checkout
      uses: actions/checkout@v2
    
    # Build project
    - name: Build
      run: |
        cd Kwarchart
        set -o pipefail && xcodebuild clean build -scheme Kwarchart CODE_SIGNING_ALLOWED=NO
    
    # Run tests

